### ISSUE TITLE
怎么在aarch64上安装

### ISSUE THREAD

**Issue by wwhwwxlz** [broadinstitute/viral-ngs#1013]
<img width="522" alt="Snipaste_2024-09-20_10-41-47" src="https://github.com/user-attachments/assets/b25a7c7c-febe-4d2a-8b76-bc42a2b51bc6">

**Comment by tomkinsc** [comment]
**A conda package for viral-ngs is no longer supported.**

**_This_ repository ([`broadinstitute/viral-ngs`](https://github.com/broadinstitute/viral-ngs)) is deprecated; development now occurs in the following locations:**
* https://github.com/broadinstitute/viral-core
* https://github.com/broadinstitute/viral-assemble
* https://github.com/broadinstitute/viral-phylo
* https://github.com/broadinstitute/viral-classify

------

The functionality of viral-ngs is now available via the pipelines here:
* https://github.com/broadinstitute/viral-pipelines

Pipeline documentation:
* https://viral-pipelines.readthedocs.io/en/latest/

The functionality of viral-ngs is also available in the following OCI (Docker) images:
* https://quay.io/repository/broadinstitute/viral-core
* https://quay.io/repository/broadinstitute/viral-assemble
* https://quay.io/repository/broadinstitute/viral-phylo
* https://quay.io/repository/broadinstitute/viral-classify

We target execution on x86-64; aarch64 (ARM) is not currently supported, though depending on the container runtime you may (or may not) be able to run the images on aarch64 with x86-64 emulation via QEMU (or Rosetta on macOS).
 * For running x86-64 images on aarch64 on Linux: 
   * https://github.com/dbhi/qus
   * https://github.com/multiarch/qemu-user-static
 
* x86-64 images on aarch64 on macOS:
  * https://github.com/abiosoft/colima
  * https://medium.com/@guillem.riera/the-most-performant-docker-setup-on-macos-apple-silicon-m1-m2-m3-for-x64-amd64-compatibility-da5100e2557d
