### ISSUE TITLE
Toolify MAFFT

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#118]
Create new Tool subclass for the MAFFT multi-aligner, available here: http://mafft.cbrc.jp/alignment/software/

MAFFT has precompiled MacOSX and Linux binaries, as well as source.  Try the Linux "portable package" version (not the RPM or DEB version) and the Mac "all-in-one" version (basically, don't ever assume you have root privs).  If the Linux binary succeeds on Travis as well as Broad CentOS (copper, tin, nickel) and Broad RHEL (gold, silver), then we're all set and feel free to skip the source-compile installer.  Otherwise, you might need to implement a compile-from-source step.

The MUSCLE tool has an example of a two-installer approach depending on the OS.  If the OS is Linux or Darwin x86, two install methods are appended: the first downloads the precompiled binary, the second downloads and unpacks the source and calls make.  If the OS is not one of those two known ones, then only the source installer is appended.

nosetests -v test.unit.test_tools.TestToolsInstallation will tell you if your installer succeeded.  On your local Mac checkout, it may fail on some other tools (like m-vicuna and v-phaser2) unless you have a special build environment set up, but you can ignore those errors.

**Comment by tomkinsc** [comment]
Addressed in #120
