### ISSUE TITLE
Create simple MAFFT command line entry point

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#119]
In interhost.py, create a new command called "align_mafft".  It should take one or more input fasta files and produce one output fasta alignment file.  You may expose some of MAFFT's optional parameters via argparse.  Some of the ones that we will likely use include: --localpair --maxiterate --reorder --ep --preservecase and --thread.

Depends on #118

**Comment by tomkinsc** [comment]
Addressed in #120
