### ISSUE TITLE
update iSNV pipeline to use pre-built alignments

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#133]
intrahost.py merge_to_vcf currently has an --assemblies required input parameter that takes in a ton of fasta files (one per sample).  It then pairwise aligns everything before doing anything useful, and this often takes an hour or so, and is very unoptimal.

Instead, it should take in alignments in an --alignments required input parameter that takes in one aligned fasta file per chromosome/segment.  This must contain all samples as well as the reference genome.

Also update the Snakemake rule (rule isnvs_vcf in intrahost.rules) accordingly. 

This depends on #127 .

**Comment by tomkinsc** [comment]
In updating the Snakemake rule (isnvs_vcf in intrahost.rules), should a multiple alignment including the reference be performed (via mafft?) as part of the isnvs_vcf rule, or should that be assumed to be a prerequisite for the rule that will occur elsewhere beforehand? A call to `./interhost.py multichr_mafft`could be added as the first step in the list of commands to run as part of the rule, accepting the list of assembly files (assuming the assemblies have the same number of chromosomes).

**Comment by tomkinsc** [comment]
Following a live discussion with @dpark01 , multichr_mafft alignment of assemblies will be assumed to be a step preceding isnvs_vcf.

**Comment by tomkinsc** [comment]
Included in ef8e045b0f4628cf1a974a356668099f31d348cd
