### ISSUE TITLE
update location of dynamically-linked library specified in variant_caller?

### ISSUE THREAD

**Issue by tomkinsc** [broadinstitute/viral-ngs#136]
This may be a quirk of my setup (OSX 10.10.4 with Xcode 6.4 installed and gcc 4.9 via [Homebrew](http://brew.sh/)), but I had to change the variant_caller binary to have the correct location for the libgomp.1.dylib library via the `install_name_tool` command, as described [here](http://stackoverflow.com/a/13421926):

    sudo install_name_tool -change /usr/local/opt/gcc49/lib/gcc/x86_64-apple-darwin13.4.0/4.9.1/libgomp.1.dylib /usr/local/opt/gcc/lib/gcc/4.9/libgomp.1.dylib /Users/tomkinsc/git-repositories/viral-ngs/tools/binaries/V-Phaser-2.0/MacOSX/variant_caller

Without this fix, attempts to run commands that would call variant_caller (including unit tests) would result in the following error:

    tools.vphaser2: DEBUG: OMP_NUM_THREADS=4 /Users/tomkinsc/git-repositories/viral-ngs/tools/binaries/V-Phaser-2.0/MacOSX/variant_caller -i /Users/tomkinsc/git-repositories/viral-ngs/test/input/TestPerSample/in.indels.bam -o /var/folders/bx/90px0g1n1v122slzjnyvrsk5gn42vm/T/tmp-TestPerSample-Ykv2o6/tmpvsT9FGvphaser2
    tools.vphaser2: ERROR: dyld: Library not loaded: /usr/local/opt/gcc49/lib/gcc/x86_64-apple-darwin13.4.0/4.9.1/libgomp.1.dylib
    Referenced from: /Users/tomkinsc/git-repositories/viral-ngs/tools/binaries/V-Phaser-2.0/MacOSX/variant_caller
    Reason: image not found

**Comment by tomkinsc** [comment]
This also appears to be an issue with mvicuna, at least for my setup.

**Comment by tomkinsc** [comment]
So it *does* work to copy the .dylib to the same directory as the binary and then change the link to be relative.

**Comment by tomkinsc** [comment]
The command to use to set the binary to use a relative path to the library makes use of the `@executable_path` variable:

`install_name_tool -change /usr/local/opt/gcc49/lib/gcc/x86_64-apple-darwin13.4.0/4.9.1/libgomp.1.dylib @executable_path/libgomp.1.dylib ./variant_caller`

**Comment by dpark01** [comment]
I'm not sure I'd close the issue until you merge a pull request back into master that introduces the fix?  What changes to the repo would fix this? It sounds like:

1. use install_name_tool to make the library reference relative (and commit the altered osx binary back to github)
2. do we still have to add a symlink or is there no step 2?

**Comment by tomkinsc** [comment]
The altered OSX binary is in my branch (`ct-multialign`), but not yet in `master`.

We could either have the user create a symlink to the dylib file, or we could distribute it ourselves. The latter seems like a better option if there aren't issues with it being licensed under [GPL v3](https://gcc.gnu.org/onlinedocs/libgomp/Copying.html#Copying).
