### ISSUE TITLE
Travis nose tests with capture

### ISSUE THREAD

**Issue by yesimon** [broadinstitute/viral-ngs#182]
Currently tests are run with `-s / --nocapture`, which doesn't capture stdout/stderr so they get printed to the logs, making them overly verbose in travis. The goal is to mimic standard unittest behavior which is to capture logs unless the test fails. Unfortunately nose doesn't capture subprocess / `os.system` output, so we will need to migrate all corresponding calls to something that makes sense, like the utility function `run_and_print`.

**Comment by tomkinsc** [comment]
Before I replace all of the calls, how's this?

```python
#!/usr/bin/python
# outtest.py

import sys
import subprocess
import functools


def run_with_capture(*args, **kwargs):
    """
        captures the output and error of a subprocess 
        call, and pipes them to stdout and stderr. 
        This is helpful because normally nosetests does not 
        capture out/err from subprocess calls.
    """
    sp = subprocess.Popen(*args,
                          stdout=subprocess.PIPE,
                          stderr=subprocess.PIPE,
                          **kwargs)
    out, err = sp.communicate()
    if out:
        sys.stdout.write(out.decode("UTF-8"))
    if err:
        sys.stderr.write(err.decode("UTF-8"))

    return sp.returncode


def test_func1():
    print("passing case, from the script directly")
    retcode = run_with_capture(["echo", "passing case, from the subprocess"])
    print("ret code, subprocess call in passing case: ", retcode)
    assert True


def test_func2():
    print("failing case, from the script directly")
    retcode = run_with_capture(["echo", "failing case, from the subprocess"])
    print("ret code, subprocess call in failing case: ", retcode)
    assert False

```

try by running `nosetests`

**Comment by yesimon** [comment]
The biggest drawback is that stdout and stderr are separated into blocks after capture and printed one block after another whereas during process execution they will be interleaved, which can lead to confusing logs from the subprocess. That's why I opted to join them by default, since most programs aren't very unixy about using stdout as a pure datastream.

**Comment by tomkinsc** [comment]
That's reasonable, let's go with your `run_and_print `.

**Comment by dpark01** [comment]
I don't know if this has already been addressed, but any reason not to just run nose without the -s / --nocapture? I think I dropped them in there at one point trying to get pysam to work, but it never ended up working anyway so it probably doesn't matter.

**Comment by tomkinsc** [comment]
Removing -s / --nocapture would help, but as @yesimon mentioned, output from subprocess.check_call() would not be captured by nose and would still appear in logs. Since the subprocess calls are responsible for much of the output, the impact of removing -s / --nocapture would be minimal. Having Popen() pipe the out/err so we can explicitly write it to stdout solves that.

**Comment by tomkinsc** [comment]
In #236
