### ISSUE TITLE
convert config.json file to yaml, add config setup helper script?

### ISSUE THREAD

**Issue by tomkinsc** [broadinstitute/viral-ngs#185]
In setting up the computational pipeline for execution via Snakemake, modification of the `config.json` file is currently a very manual process. It may not be immediately obvious which settings a user must change, which settings are optional, what values are valid, and how the values impact execution of the pipeline. Since the file is in `json` format, comment strings are not permitted and settings cannot be documented inline.

The config file should perhaps be converted to YAML format, which permits inline comments. 

In addition, a helper script could be provided to query the user for values to populate the config file. Of particular importance are the minimum assembly quality thresholds (fraction of reference, fraction unambiguous),  the list of NCBI accessions comprising the reference genome, as well as file paths for the data directory, the depletion databases, and the (optional) lastal db accessions file. In contrast to inline documentation, the script could also set parameters based on the user's environment, such as the number of CPU cores.

**Comment by dpark01** [comment]
Also their email address!

Some of the values can have suggested defaults (fraction of reference, etc)

**Comment by tomkinsc** [comment]
Absolutely, though it will work with any value for email until rate limits become an issue.

**Comment by tomkinsc** [comment]
Annotated yaml config in PR #187. Script probably not necessary at this point.
