### ISSUE TITLE
Convert MUMmer tool to Conda-based install

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#205]
Will need to add package to bioconda channel. Version 3.23 specifically.
Obtain from here:
https://sourceforge.net/projects/mummer/files/mummer/3.23/
Run make. That's it. There's a dozen or so binaries as part of this suite and we use many of them (nucmer, promer, show-aligns, show-tiling, etc).

**Comment by tomkinsc** [comment]
In #206.
