### ISSUE TITLE
NCBI genbank submission filenames

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#224]
Shirlee reports that running snakemake annot_all creates samplename.tbl files instead of samplename-<chr_idx>.tbl files as expected by downstream steps and subsequently fails. Haven't looked into it yet myself.

**Comment by tomkinsc** [comment]
Resolved, I believe? It seems the problem was related to running a newer version of viral-ngs on data created before the multi-segment improvements were added to viral-ngs. Sample names in assembly fasta files lacked the "-num" suffix `>sample-3`. This confused some downstream steps.
