### ISSUE TITLE
change trinity version string to reflect new version string on bioconda

### ISSUE THREAD

**Issue by tomkinsc** [broadinstitute/viral-ngs#263]
See: https://github.com/bioconda/bioconda-recipes/issues/1312
Once the version changes on [anaconda.org](https://anaconda.org/bioconda/trinity), we can update it here. The change should be:
`2011_11_26` ➜  `date.2011_11_26`

**Comment by dpark01** [comment]
let's do this in June

**Comment by tomkinsc** [comment]
So this isn't a change of the version of Trinity we're using, just of the string we need to use to retrieve it.

**Comment by dpark01** [comment]
If upstream bioconda forces a change, then we'll need to change this, but fixing Trinity on OSX bears no relationship to any current dev priorities.

**Comment by tomkinsc** [comment]
Understood and acknowledged.
