### ISSUE TITLE
Trinity needs to prepend PATH with conda bin path

### ISSUE THREAD

**Issue by yesimon** [broadinstitute/viral-ngs#267]
Otherwise it picks up the system java version which may be newer and fail to run

**Comment by dpark01** [comment]
Wait, does the conda version of Trinity not include our fixes that allow it to work fine on Java 1.7 and 1.8?

**Comment by yesimon** [comment]
Thanks for noticing! @tomkinsc  Looks like the patch is not patching out the `die` part of the java version check

**Comment by tomkinsc** [comment]
I pulled the latest Trinity v1 package from [anaconda](https://anaconda.org/bioconda/trinity/files), and to me it looks like the [patch](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/trinity/date.2011_11_26/Trinity.pl.patch#L8-9) is being applied. The changes to lines 211-212 look identical to those created by our prior [DownloadAndBuildTrinity](https://github.com/broadinstitute/viral-ngs/blob/master/tools/trinity.py#L84-86).

**Comment by tomkinsc** [comment]
For conda-based installs to work in the first place, users will need to have conda on their PATH, which also means that the conda install of java will be picked up.

**Comment by tomkinsc** [comment]
So I think the issue may be that conda installs the openjdk flavor of java, rather than oracle java, and the version string being checked by Trinity (even after being patched) doesn't match when openjdk is being used. I'll change the patch to add openjdk as an alternate match

**Comment by tomkinsc** [comment]
PR pending with fix: https://github.com/bioconda/bioconda-recipes/pull/1352

**Comment by dpark01** [comment]
Great, once that's in, go ahead and PR viral-ngs accordingly. Also, once that's done, is there any reason that Trinity needs to live in its own conda environment, or can it go back to living with everyone else ("default")?

**Comment by yesimon** [comment]
No the problem is the conflict between perl and perl-threaded, which is not
as easily resolved.

**Comment by tomkinsc** [comment]
No PR should be needed, since viral-ngs will pull the latest build when installing Trinity. What's the specific issue with perl vs perl-threaded?

**Comment by yesimon** [comment]
Trinity requires `perl-threaded` while krona requires `perl`. Depending on the order they get installed, trinity might find a perl that won't work. That's why it was split into its own environment.

**Comment by tomkinsc** [comment]
Ok. Why can't krona use `perl-threaded`?

**Comment by yesimon** [comment]
Because it has a dep on `perl`. Apparently `perl-threaded` has a significant performance penalty due to synchronization overhead. Therefore packages prefer to dep on `perl` if possible.

**Comment by tomkinsc** [comment]
Krona currently has a dependency on `perl`. It can and should be changed to use `perl-threaded`, since the performance argument [doesn't really hold water](https://mail-archives.apache.org/mod_mbox/perl-modperl/200311.mbox/%3C3FB298A0.3050503@stason.org%3E), and the official bioconda [guidelines](https://github.com/bioconda/bioconda-recipes/blob/master/GUIDELINES.md#perl) require the use of `perl-threaded`.

**Comment by tomkinsc** [comment]
I've put in a PR (https://github.com/bioconda/bioconda-recipes/pull/1357) to move krona to use `perl-threaded`. Trinity can join the other packages in the default conda env once it is accepted, right?

**Comment by yesimon** [comment]
Yes it can go in the default env after that's through. Although isn't that link pretty definitive that threads decrease performance? The question is whether anybody cares about 5%, and if you're using conda bin packages, you definitely aren't concerned about performance :wink:

**Comment by dpark01** [comment]
Krona has got to be almost instantaneous to run, right? Please tell me average runtime is under 20sec...

--
Daniel J. Park, PhD
Group Leader, Viral Computational Genomics
Broad Institute of MIT and Harvard
Tel: +1-617-714-8526
dpark@broadinstitute.org
http://www.broadinstitute.org/bios/daniel-park

**Comment by yesimon** [comment]
I meant it as a general comment about the conda+perl interaction. Krona has instant runtime once the db is created.

**Comment by tomkinsc** [comment]
OK, krona in bioconda now uses `perl-threaded`.

**Comment by dpark01** [comment]
Wait, what db?  metagenomics.krona(...) and
tools.krona.Krona.import_taxonomy(...) make no mention of a db. As far as I
can tell, the input files and output files are all small O(1) tiny things.

**Comment by yesimon** [comment]
It needs a taxonomy database, which it stores and detects in its own opt directory by default. I'll make it configurable along with the krona unit test.
