### ISSUE TITLE
Update Diamond version?

### ISSUE THREAD

**Issue by tomkinsc** [broadinstitute/viral-ngs#279]
The viral-ngs wrapper for Diamond [currently uses](https://github.com/broadinstitute/viral-ngs/blob/master/tools/diamond.py#L17) v0.7.9, while the Diamond package [on bioconda](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/diamond) is v0.7.10. Can we use version v0.7.10 and add a `CondaPackage()` install method to our wrapper?

**Comment by dpark01** [comment]
Done
