### ISSUE TITLE
Add documentation of test infrastructure

### ISSUE THREAD

**Issue by tomkinsc** [broadinstitute/viral-ngs#284]
This is something for @dpark01, @yesimon, and @tomkinsc. We should consider adding a `README.md` file to `test/` noting our test infrastructure, the tools used, some of the rationale behind our usage, and basic getting started information. Possible things to include:

- Travis Linux with Py3 is the authoritative test server
- Tox is present for convenience (local use only, not currently in use on Travis)
- The function `util/misc.py`:`run_and_print()` exists so nose can capture subprocess output
- Info on the various style dotfiles (`.flake8`, `.pylintrc`, `.style.yapf`), where they are used (intended for manual use? post-commit hook?) Are any of them vestigial? 
- Details on some of the more recent changes to coverage
- That we're using `nose` and not the built-in Python `unitttest` module to allow for generative testing in `test/unit/test_tools.py`:`testAllToolInstallers()`
- Details on what data is stored in the Travis cache
- Details on third-party resources (why we're pulling in a GATK+Novoalign tarball)
- The intention and breakdown between our `unit` tests and `integration` tests: specifically prose descriptions of what common usage the integration tests cover (which aspects of the pipeline), and any important backstory behind the input data
- The usage of `util.file.get_test_input_path()` and any relevant information on how the test input data files were created

**Comment by dpark01** [comment]
Also, import some discussion from PR #292 to such documentation. Perhaps in a separate travis/README.md or in the same test/README.md.

**Comment by tomkinsc** [comment]
It's only a start, but #334 includes a section on testing. Please feel free to add anything you think may be helpful for those contributing to viral-ngs in the future.
