### ISSUE TITLE
publicly host required databases

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#307]
Currently, people can download our code, install our dependencies, and run the pipeline themselves, with the exception of seven data resource files that are currently necessary.

Three metagenomic databases:
- kraken db
- diamond db
- krona db

And four host depletion databases:
- three bmtagger dbs
- one blast db

All of these should be wrapped up and provided as publicly hosted .tar.gz and .tar.lz4 files in some easily accessible place that offers sufficiently fast downloads (especially for the kraken db). My first thought is in gs://sabeti-public, but S3 or Github LFS or such would be fine too.

**Comment by tomkinsc** [comment]
GitHub LFS wouldn't be bad if we're ok with the [cost](https://help.github.com/articles/billing-plans-for-git-large-file-storage/). I might suggest creating a separate repository if we go that route ("viral-ngs-dbs"?).

Otherwise, gs://sabeti-public is easy enough.

I'll have to get a copy of the metagenomic databases from @yesimon.

**Comment by dpark01** [comment]
I don't think adding any auto-downloading/staging machinery is in-scope for this issue, but maybe add the links to the comments in config.yaml so people know where to find the resources and obtain them themselves.

**Comment by tomkinsc** [comment]
This is in progress, with links being added to the docs and the config file in #317.

**Comment by dpark01** [comment]
Is this one done?

**Comment by tomkinsc** [comment]
Almost. There have been a few md5 mismatches when uploading the large db files, so I'm still retrying.

**Comment by tomkinsc** [comment]
All uploaded! Closing this issue.
