### ISSUE TITLE
tolerate empty (or near-empty) input

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#308]
Make more steps, particularly metagenomic steps, robust to empty (or near-empty) inputs (producing semantically appropriate outputs in cases with no data).

Create integration tests for much of the assembly pipeline that tests properly functioning empty-input scenarios for most steps (and allows PoorAssemblyError for the scaffold-impute step).

**Comment by tomkinsc** [comment]
One problem spot:
    Picard seems to fails for empty bam input. Observed in `./taxon_filter.py deplete_human`

**Comment by tomkinsc** [comment]
Another on `kraken-report` where no classified reads are present in input

**Comment by tomkinsc** [comment]
A DNAnexus [job failed](https://platform.dnanexus.com/projects/Bq1xjF0010q3Qv8V70vjXpV8/monitor/job/BxJx7X0010qJ124zYV9XxFXx), possibly due to bmtagger receiving minimal input ([1KB bam file](https://github.com/broadinstitute/viral-ngs/files/311871/ExtCtrl2.bam.zip) with only 12 reads).

**Comment by dpark01** [comment]
WIP. Current status update:

I've restructured bits of code so it's obvious where the fixes would go, and I've started to put in unit tests that fail on the use cases that we want to fix. But I haven't yet gotten some of them to fail properly, particularly on some of these "almost empty" scenarios. I want to get the test cases solid before actually fixing any code.

The almost-empty scenarios are probably ones where the output is empty, or no reads are classifiable, or the hits from a tool are empty. Since our unit tests use stripped down test databases, I'll need to modify the read set accordingly.

**Comment by dpark01** [comment]
Update: I have good (failing) tests on our depletion steps for empty inputs/outputs.  Kraken took a while to hunt down because apparently, Kraken fixed the divide-by-zero errors in 0.10.6 (what our current master uses) but they exist in 0.10.5 (which is what our old code in DNAnexus uses)
