### ISSUE TITLE
problem with pytest.ini

### ISSUE THREAD

**Issue by sbecuwe** [broadinstitute/viral-ngs#315]
I'm trying to install viral-ngs 1.4.2, downloaded from the [releases](https://github.com/broadinstitute/viral-ngs/releases) web page, following the instructions on [readthedocs](http://viral-ngs.readthedocs.io/en/latest/install.html), but it seems there's a problem with the default pytest.ini. I'm using pytest 2.9.1.
```
$ py.test -v test/unit/test_tools.py
usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: -n --cov-report= --cov broad_utils --cov illumina --cov assembly --cov interhost --cov intrahost --cov metagenomics --cov ncbi --cov read_utils --cov reports --cov taxon_filter --cov tools --cov util test/unit/test_tools.py
  inifile: /dev/shm/viral-ngs-1.4.2/pytest.ini
  rootdir: /dev/shm/viral-ngs-1.4.2
```
Thanks for your feedback!

**Comment by dpark01** [comment]
Hi, we just ran into this issue internally as well. For now, the fix is to pip install -r requirements-tests.txt as well. Beyond that though, @tomkinsc is working on a cleaner install process more generally.

**Comment by dpark01** [comment]
Let me know if the above suggestion addresses your installation needs.

#310 should obviate this
