### ISSUE TITLE
Create fake taxon for spike-ins

### ISSUE THREAD

**Issue by tomkinsc** [broadinstitute/viral-ngs#339]
The Kraken DB and Krona report should include a fake taxon for spike-ins. The path to the fasta file is noted in the [config file](https://github.com/broadinstitute/viral-ngs/blob/master/pipes/config.yaml#L40).

**Comment by yesimon** [comment]
I will be reusing taxon id 32630: synthetic construct already with 6M sequences in NCBI.

**Comment by tomkinsc** [comment]
Ok! That includes sequences for all of our synthetic spike-ins?

**Comment by yesimon** [comment]
I don't think so? It's just kind of a bucket taxon for people to assign artificial stuff.

**Comment by dpark01** [comment]
Okay, can we check if our 32 sequences in /idi/sabeti-scratch/kandersen/references/other/ercc_spike-ins.fasta might already be in NCBI under some accession that already has a properly assigned taxon id (32630)? If not, @yesimon how easy is it to add custom sequences to your kraken & diamond DBs that are not actually in genbank? You'd have to add custom entries to their taxon DBs as well and maybe fake accessions and stuff.

**Comment by dpark01** [comment]
Ok, do you think the best way to do this is simply to add 32 accession numbers to the kraken DB as well, and everything downstream will automatically work (since they already have proper taxon ids)?  Here is a list of 32 accession numbers I *think* should correspond to our ERCC's but someone ought to double check.

```
KC702164.1
KC702165.1
KC702171.1
KC702176.1
KC702177.1
KC702179.1
KC702180.1
KC702181.1
KC702182.1
KC702183.1
KC702184.1
KC702187.1
KC702189.1
KC702190.1
KC702193.1
KC702194.1
KC702195.1
KC702205.1
KC702207.1
KC702210.1
KC702212.1
KC702214.1
KC702217.1
KC702219.1
KC702222.1
KC702227.1
KC702230.1
DQ883670.3
DQ883671.3
DQ883673.3
DQ883682.3
DQ883685.3
```

**Comment by yesimon** [comment]
Well the seq -> taxon id mapping is inserted directly in the fasta headers so I'm just trying to rebuild the database.

**Comment by yesimon** [comment]
Also I mentioned this in the slack channel but our fasta file has some differences compared to the reference accessions (albeit 99% identity, ~10 mismatch/gap out of 1k bp each).

**Comment by dpark01** [comment]
Status check: where are we on this one? I don't think those mismatches really are an issue. @yesimon , if you have a new kraken db tarball, @tomkinsc can post gz/lz4 versions to a public bucket and we can relay that onwards to @yifei-men . My understanding is that the diamond and krona databases would not need to change at all, correct?

**Comment by yesimon** [comment]
My job to rebuild kraken has been waiting long queue the entire time :( I'll try LSF

**Comment by tomkinsc** [comment]
Not sure how long the job queue is at this point, but BITS@Broad has scheduled maintenance that will be disruptive to the cluster, starting this Saturday. If LSF isn't a quick queue, it may make sense to wait until Sunday or Monday.
