### ISSUE TITLE
relax trimmomatic qual filters

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#357]
Reduce LEADING/TRAILING from 20 to 15 for the pre-trinity filter.

https://github.com/broadinstitute/viral-ngs/blob/master/taxon_filter.py#L140-L141

**Comment by tomkinsc** [comment]
I'll probably expose the cutoffs as knobs we can turn.

**Comment by dpark01** [comment]
perfect!

**Comment by tomkinsc** [comment]
Do we want to change the SLIDINGWINDOW quality threshold as well? [Looks like](http://www.usadellab.org/cms/?page=trimmomatic) it's the second int in that parameter.

**Comment by dpark01** [comment]
Sure... MINLEN too while you're at it?

So we'll expose optional params in argparse that default to our custom mix
of defaults?

**Comment by tomkinsc** [comment]
We will. I have MINLEN among the newly exposed args.

**Comment by tomkinsc** [comment]
Addressed by #358
