### ISSUE TITLE
'py.test test/unit test/integration' fails

### ISSUE THREAD

**Issue by haydenm** [broadinstitute/viral-ngs#362]
Running `py.test test/unit test/integration` raises 4 failures because Python is unable to `import pysam`. However, running `py.test test/unit` succeeds and running `py.test test/integration` succeeds. This could be a bug with `py.test`, or perhaps I'm not understanding how it works.

**Comment by dpark01** [comment]
hm... I'm not actually experiencing this error myself... what does pip freeze say your pysam version is?

**Comment by haydenm** [comment]
It's 0.8.3.

**Comment by tomkinsc** [comment]
I can't seem to replicate this either. Are you still seeing this, @haydenm, or can I close the issue?

**Comment by haydenm** [comment]
Nope, I just tried and it passed. (I do get errors on the metagenomics integration tests, but I always have and that's a separate issue.)
