### ISSUE TITLE
Trim whitespace when handling sample names from barcode and SampleSheet files

### ISSUE THREAD

**Issue by tomkinsc** [broadinstitute/viral-ngs#368]
Currently, users may inadvertently introduce trailing spaces as part of sample names in tab-delimited barcode or sample sheet files. This can cause failures when running the Snakemake pipeline, and can be difficult to debug. Sample names should probably have trailing spaces stripped via `sample_name.strip()` wherever these files are read in.

**Comment by dpark01** [comment]
why preserve tabs? I'd say sample_name.strip() (strip from both sides). The sample name variable won't be populated until after a tab-file-parser is already working on it...

**Comment by tomkinsc** [comment]
You're right!

**Comment by tomkinsc** [comment]
Hopefully addressed in #383.
