### ISSUE TITLE
Sanitize sample names going in to metagenomics functions; sanitize/replace parentheses in string_to_file_name()

### ISSUE THREAD

**Issue by tomkinsc** [broadinstitute/viral-ngs#372]
See [this failure](https://platform.dnanexus.com/projects/Bq29k680jy1JF3gvkk3Gjf11/monitor/analysis/BxbVKPQ0jy17Vygj7b4Q8bVJ). Kraken classification failed seemingly due to an open-paren `(` being present in the file names for samples. We should sanitize the sample names via [`util.file.py:string_to_file_name()`](https://github.com/broadinstitute/viral-ngs/blob/master/util/file.py#L345), and that function should escape or replace parentheses.

**Comment by tomkinsc** [comment]
Since `string_to_file_name()` is used during demux, this should mostly be addressed for the pipeline by #373.

**Comment by dpark01** [comment]
done!
