### ISSUE TITLE
Consider adding conda dependencies to pin file

### ISSUE THREAD

**Issue by tomkinsc** [broadinstitute/viral-ngs#378]
See: http://conda.pydata.org/docs/faq.html#pinning-packages
Since conda updates packages by default, later installs can cause previous installs to be updated if doing so resolves dependencies for the later installs. A pin file solves this at a risk of erroring our when installing a package with incompatible dependencies.

We will need to add the version to the pin file on install, and maybe remove it on uninstall/update.

**Comment by dpark01** [comment]
How about adapting or replacing requirements-conda.txt and making sure travis/install-tools.sh works on the new file?

**Comment by dpark01** [comment]
On a related note, we could add some sort of test to test_tools.py (it would have to execute after all other tool tests run) that verifies that "conda list" is reporting the same versions we asked for in the pin file.

**Comment by tomkinsc** [comment]
I'd like to move things toward a common conda environment file, but there are [some bugs](https://github.com/conda/conda/issues/2800) in how `conda env` creates and imports environment files.
