### ISSUE TITLE
make SampleSheet reader robust to all sorts of CSV files

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#381]
Currently, the SampleSheet reader, when operating on CSV files, does a simple string split on commas. This doesn't handle quoted cells with commas in them, which are among the possibilities of what the Illumina MiSeq can generate. We should switch the CSV reading code path for SampleSheet to use the `csv` module in python, which handles all those scenarios (do not use for simple tab file inputs).

Here is an [example failed run](https://platform.dnanexus.com/projects/Bq29k680jy1JF3gvkk3Gjf11/monitor/analysis/Bxk6QkQ0jy1355qGZJyB1K3b) on DNAnexus.

Example failed SampleSheet is attached (rename .csv.txt to .csv, github does not accept .csv attachments): [SampleSheet.csv](https://github.com/broadinstitute/viral-ngs/files/337045/SampleSheet.csv.txt)

**Comment by tomkinsc** [comment]
Is there a historical reason (some edge case) why we are not already using the csv module?

**Comment by dpark01** [comment]
Not really​, I think it was assumed that the CSVs coming out of Illumina's
software was going to be a simple subset of the realm of possibilities.

**Comment by tomkinsc** [comment]
Hopefully addressed in #383.
