### ISSUE TITLE
Don't fail if path contains spaces

### ISSUE THREAD

**Issue by iljungr** [broadinstitute/viral-ngs#39]
Currently, most of our commands will fail if any of the paths contain spaces or other characters interpreted by the shell. The reason is that they are getting interpreted by the shell twice, once when the user invokes our command and then again when we call os.system. This can easily be fixed by putting single quotes around all the paths in our call to os.system. Alternatively, we could use subprocess.call instead of os.system, since that is now the recommended way to do this, but that would be more work and I'm not sure what the benefit is.

**Comment by dpark01** [comment]
Most things have converted to subprocess.call at this point (or similar), I think the main exception is the download & build tool installers.
