### ISSUE TITLE
expose intrahost optional params in config.yaml

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#412]
The following optional parameters to intrahost steps should be exposed in config.yaml for users to tune as desired, perhaps with default values shown in comments e.g. the assembly_nucmer parameters.

- **intrahost.py vphaser_one_sample**  --minReadsEach and --maxBias
- **intrahost.py merge_to_vcf** --naive_filter

**Comment by tomkinsc** [comment]
In #413
