### ISSUE TITLE
Feature for removing duplicates in `plot_coverage` and `align_and_plot_coverage`

### ISSUE THREAD

**Issue by haydenm** [broadinstitute/viral-ngs#415]
An optional argument would be a helpful addition to the `reports.py::align_and_plot_coverage` tool:
- `--remove-duplicates`. This would use Picard's `MarkDuplicates` on the alignment and then `samtools` to filter the duplicates. It would plot coverage of just the non-duplicates.

**Comment by tomkinsc** [comment]
In #416.
