### ISSUE TITLE
snpEff executions hang

### ISSUE THREAD

**Issue by haydenm** [broadinstitute/viral-ngs#422]
Calls to `snpEff` made in `tools::snpeff::execute()` never close. Specifically, they hang [here](https://github.com/broadinstitute/viral-ngs/blob/b7aa1a57ddf8b0e267e9577f81ef836730c138e2/util/misc.py#L250). Changing `buffered=True` to `buffered=False` fixes it, so this may be an issue more broadly related to using `buffered=True`.

**Comment by tomkinsc** [comment]
Closing; addressed in #424.
