### ISSUE TITLE
Double-counting unpaired reads

### ISSUE THREAD

**Issue by haydenm** [broadinstitute/viral-ngs#427]
With the latest update to subsampling (commit 1d1d747), the final subsampled read count seems to be double-counting unpaired reads on [line 174](https://github.com/broadinstitute/viral-ngs/blob/1d1d74722db416ab71ea4094496750737ead79fe/assembly.py#L174) in cases where we fall below the subsample threshold.

For example, an output I see is 
> __main__.DenovoAssemblyError: denovo assembly (Trinity) failed. 71 reads at start. 71 reads after Trimmomatic. 71 reads after Prinseq rmdup. 71 reads after removing unpaired mates. 115 reads after subsampling.

In this particular case, if we were double-counting unpaired reads it should say `110 reads after subsampling`, so I'm not positive this is in fact the problem. (Since downsampling the unpaired reads is approximate, that could explain the discrepancy.) Regardless, the count does appear off. In this case, if the goal is to report the number of paired-end reads (counting each pair once) plus the number of unpaired reads, `n_subsamp` should be 71.

**Comment by tomkinsc** [comment]
Addressed in #443
