### ISSUE TITLE
For depletion, option to act on reads independently

### ISSUE THREAD

**Issue by tomkinsc** [broadinstitute/viral-ngs#436]
In cases where one read of a pair is a sample-human chimera and the other read is entirely sample, it should be possible for the depletion stage to preserve singleton sample reads while rejecting the chimeric half of the pair. 

To support this, the earlier pipeline stages will likely need to be updated to tolerate single-end reads, as mentioned in #238, and it may be helpful to revisit replacing bmtagger with a different depletion strategy.

**Comment by dpark01** [comment]
Uh, in general I don't know if this is a good idea

**Comment by tomkinsc** [comment]
I'll close this for now
