### ISSUE TITLE
rebuild kraken db for diversity

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#440]
Currently, kraken db is built on RefSeq entries (one per species). This might be okay for eukaryotic / bacterial, but at least for viral, we should build it on a much more comprehensive sequence space. Recent ACEGID trainings have exposed severe limitations with detecting LASV and other diverse viruses. @haydenm has a nice accession list for human viral pathogens.

Deadline: Sept 2016 (in advance of FUO work in Nigeria).

**Comment by tomkinsc** [comment]
@yesimon: Is this complete, in the form of: https://storage.cloud.google.com/sabeti-public/meta_dbs/kraken_full-and-mosquito-and-all_human_viral.tar.gz ?

**Comment by yesimon** [comment]
Yes, but it includes mosquito as well!
