### ISSUE TITLE
spikein_report's call to bwamem_idxstats

### ISSUE THREAD

**Issue by haydenm** [broadinstitute/viral-ngs#460]
The rule `spikein_report` in `reports.rules` calls [`bwamem_and_idxstats`](https://github.com/broadinstitute/viral-ngs/blob/master/pipes/rules/reports.rules#L61) but the function is named [`bwamem_idxstats`](https://github.com/broadinstitute/viral-ngs/blob/master/read_utils.py#L1161). Also, the arguments passed are `{input} {params.spikeins_db} {output}`, which differ from the positional arguments the function accepts. Should the rule be changed to call `bwamem_idxstats` and the function changed to no longer accept [`outBam`](https://github.com/broadinstitute/viral-ngs/blob/master/read_utils.py#L1184)?

**Comment by dpark01** [comment]
Yeah so, what you're saying is that this:
```
shell("{config[bin_dir]}/read_utils.py bwamem_and_idxstats {input} {params.spikeins_db} {output}")
```

should be changed to this:
```
shell("{config[bin_dir]}/read_utils.py bwamem_idxstats {input} {params.spikeins_db} --outStats {output}")
```

Is that right?

**Comment by haydenm** [comment]
Yes, that should do it!
