### ISSUE TITLE
Report fastqc results on raw and cleaned reads

### ISSUE THREAD

**Issue by haydenm** [broadinstitute/viral-ngs#465]
Currently viral-ngs runs fastqc only on [aligned-to-self](viral-ngs/pipes/rules/reports.rules) reads. It would be very useful to also see fastqc output on raw and cleaned reads, possibly as well as tax-filtered reads and (if reference-based assembly was run) mapped reads from `data/03_aligned_to_ref/*.realigned.bam`. fastqc is very fast, even on raw reads, so this should not affect runtime by much. The output could go in `reports/fastqc/{sample}/{raw,cleaned,...}/` or alternatively `reports/fastqc/{raw,cleaned,...}/{sample}/`.

**Comment by haydenm** [comment]
Would the best way to do this just be to update the `reports.rules` snakemake rule? It might be necessary to create separate rules for some fastqc runs, rather than just adding wildcards, because the directory of the input BAM may differ.

**Comment by dpark01** [comment]
I think it's fine to make separate rules in `reports.rules`. As long as all the outputs are specified in the "all" and "all_reports" targets.

**Comment by dpark01** [comment]
I think this old issue was basically addressed a while ago... the WDL workflows even produce fastqc reports on mapped-only dedup (post assembly) reads and taxfilt reads and such.
