### ISSUE TITLE
avoid RevertSam in deplete_human when possible

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#527]
Right now, we call RevertSam at the beginning of `deplete_human`. That's mostly just defensive for a few scenarios (e.g. someone gives us a aligned bam, etc), but in most cases (e.g. this come straight after demux) is pointless and wastes a lot of time.

Perhaps we should only RevertSam if we notice certain features of the bam coming in (e.g. it looks to be aligned) which can be queried quickly just by looking at the bam header...

**Comment by tomkinsc** [comment]
Looking at the [sam/bam spec](https://samtools.github.io/hts-specs/SAMv1.pdf), we should be able to detect aligned bam files by looking for `@SQ` lines in the header, right?

Are there other cases where we'd want to call `RevertSam`?

**Comment by tomkinsc** [comment]
In #529.
