### ISSUE TITLE
source easy-deploy-viral-ngs.sh load crashing

### ISSUE THREAD

**Issue by jrotieno** [broadinstitute/viral-ngs#593]
Just updated my viral-ngs, but seems to crash at this stage with the terminal tab just exiting. Any reasons why this might be happening?

**Comment by tomkinsc** [comment]
Sorry you have had an issue; there have been a number of changes to how viral-ngs is distributed in the last 16 hours (with more changes ongoing), due to a shift from building for bioconda to building for our [own channel](https://anaconda.org/broad-viral). To start, I would suggest updating the easy-deploy script if you have not already done so:
`./easy-deploy-viral-ngs.sh update-easy-deploy`

Then a few questions:
- Which operating system are you using for viral-ngs? (At present, there is not a macOS package built for the latest version of viral-ngs.)
- Which shell? (bash?)
- What process did you do through to update viral-ngs?

**Comment by jrotieno** [comment]
Hi Tom,

I am on MacOS and using bash.

I deleted my previous installation folders and did a fresh install using the easy-deploy set up.

Will give it another shot tomorrow morning

**Comment by tomkinsc** [comment]
Some incompatibilities have also appeared with the most recent version conda, the underlying package manager. If you do a fresh setup, try installing version 1.15.2 of viral-ngs:

`./easy-deploy-viral-ngs.sh update-easy-deploy`
`./easy-deploy-viral-ngs.sh setup --viral-ngs-version 1.15.2`

**Comment by tomkinsc** [comment]
Hi James, any success with the latest easy-deploy script and viral-ngs v1.15.2?

**Comment by jrotieno** [comment]
@tomkinsc,

I did a fresh setup, but still have terminal quitting whenever I try to load viral-ngs as

`source easy-deploy-viral-ngs.sh load`

So, I redirected the output to a file and this is the error message

`ERROR: The conda path to be created by this script is too long to work with conda (142 characters):
/Users/jotieno
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed./viral-ngs-etc/mc3
This is a known bug in conda (80 character limit): 
https://github.com/conda/conda-build/pull/877
To prevent this error, move this script higher in the filesystem hierarchy.
Saving session...
...saving history...truncating history files...
...completed.`

NB: I am running the script from my home directory.

**Comment by tomkinsc** [comment]
As that error implies, there is a current [issue](https://github.com/conda/conda-build/pull/877) where conda environments cannot be nested too deeply in the filesystem hierarchy (with path prefixes >80 characters), and it will unfortunately remain an issue until all viral-ngs dependencies, in all relevant channels, have been rebuilt with `conda-build >=2.1.5`.

I'm curious though, are you running the script from `/Users/jotieno/` or a (lengthy, nested) subdirectory of that location? If the path prefix is not actually too long (>80 characters), we'll need to debug why the script is saying it is 142 characters in length. 

1. What is the full path to the `easy-deploy-viral-ngs.sh` script?
2. How are you calling the script? (via any symlinks?)

**Comment by jrotieno** [comment]
Hi Tom,

1. The full path to the easy deploy script is /Users/jotieno/easy-deploy-viral-ngs.sh

2. I am calling the script directly from the home directory:
source easy-deploy-viral-ngs.sh load

**Comment by tomkinsc** [comment]
Ok, thanks. Could you please download and run this script and report back the output?
(be sure the `env` line does not write anything sensitive though): https://gist.githubusercontent.com/tomkinsc/0961327b8f14707af9ddf2bde109a630/raw/debug_viral-ngs_easy_deploy.sh

-Chris

**Comment by jrotieno** [comment]
@tomkinsc 

Here is the output:

> =============================================================
sourced:                   0
SHELL:                     /bin/bash
BASH_VERSION:              3.2.57(1)-release
-------------------------------------------------------------
STARTING_DIR:              /Users/jotieno
SOURCE:                    debug_viral-ngs_easy_deploy.sh
SCRIPT_DIRNAME:            .
SCRIPTPATH:                /Users/jotieno
SCRIPT:                    /Users/jotieno/debug_viral-ngs_easy_deploy.sh
-------------------------------------------------------------
sed check:                 48
which sed:                 /usr/bin/sed
-------------------------------------------------------------
which dirname:             /usr/bin/dirname
which basename:            /usr/bin/basename
which readlink:            /usr/bin/readlink
-------------------------------------------------------------
VIRAL_CONDA_ENV_PATH:      /Users/jotieno/viral-ngs-etc/conda-env
CONTAINING_DIR:            viral-ngs-etc
MINICONDA_DIR:             mc3
MINICONDA_PATH:            /Users/jotieno/viral-ngs-etc/mc3
current_prefix_length:     33
CONDA_PREFIX_LENGTH_LIMIT: 80
-------------------------------------------------------------

**Comment by tomkinsc** [comment]
That output looks fine, and is similar to what I see on my end. As you may have noticed, that script is the `easy-deploy-viral-ngs.sh` script up to the point where your earlier error message was captured. It's strange that the easy-deploy script would say the prefix is 142 characters when the debug script with the same length function indicates it at 33 characters (`current_prefix_length`). 

Sorry for all of the back-and-forth on this, but could you please post your full `easy-deploy-viral-ngs.sh` script as a [github gist](https://gist.github.com/)? I'd like to see if its self-update went wrong in some way. Thanks.

**Comment by jrotieno** [comment]
No worries, I'm more than glad to help with this!

Here is the gist for my `easy-deploy-viral-ngs.sh` script:

`https://gist.github.com/jrotieno/72fdf4894be44a323ad5ddb2b0b7fbad`

**Comment by jrotieno** [comment]
**UPDATE:**
Did an install on my MacBook Pro instead of the Mac Pro and all went well. The `easy-deploy-viral-ngs.sh` script updated, set up and loaded with no problems.

On the MacPro, however, the terminal still quits when I call `source easy-deploy-viral-ngs.sh load`. I tried the alternative `source activate /Users/jotieno/viral-ngs-etc/conda-env` on the MacPro, to which the environment loaded without quitting. Is it the same thing?

I then called `conda info -e` on both: On the MacBook I get `/Users/jotieno/viral-ngs-etc/mc3` while on the MacPro I get `/Users/jotieno/miniconda2`

What do you think?

**Comment by tomkinsc** [comment]
Nice detective work. I'm guessing it is because you already have conda on the path from `/Users/jotieno/miniconda2`. Would you be able to share the output of `env | grep -i CONDA`? Then I can look at making revisions to the script to hopefully correct the issue.

**Comment by jrotieno** [comment]
Here is the output:
`JOtieno-MacPro:~ jotieno$ env | grep -i CONDA
MANPATH=/Users/jotieno/.nvm/versions/node/v6.5.0/share/man:/Users/jotieno/miniconda2/share/man:/Library/Frameworks/Python.framework/Versions/2.7/share/man:/usr/local/share/man:/Library/Frameworks/Python.framework/Versions/3.4/share/man:/usr/share/man:/opt/X11/share/man:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/share/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man
PATH=/usr/local/opt/openssl/bin:/Users/jotieno/.rvm/gems/ruby-2.3.0/bin:/Users/jotieno/.rvm/gems/ruby-2.3.0@global/bin:/Users/jotieno/.rvm/rubies/ruby-2.3.0/bin:/Users/jotieno/.nvm/versions/node/v6.5.0/bin:/Software/apache-maven-3.3.9/bin:/Users/jotieno/miniconda2/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/sbin:/Users/jotieno/Desktop/Software:/Users/jotieno/Desktop/Software/paml4.8/bin:/Users/jotieno/Desktop/Software/PhyML-3.1:/Users/jotieno/Desktop/Software/ncbi_cxx--7_0_0/scripts/common:/Users/jotieno/Desktop/Software/picard:/Library/Frameworks/Python.framework/Versions/3.4/bin:/Users/jotieno/Desktop/Software/fastq_screen_v0.5.2:/Users/jotieno/Desktop/Software/BRIG-0.95-dist:/James_Otieno/Softwares/PhyML-3.1:/Users/jotieno/Desktop/Software/kmlocal-1.7.2/bin:/Users/jotieno/Desktop/Software/seqan-master/bin:/Users/jotieno/Desktop/Software/homer/.//bin:/Users/jotieno/Desktop/Software/weblogo:/Users/jotieno/Desktop/Software/bpp3.1:/Users/jotieno/Desktop/Software/paml4.8/bin:/Users/jotieno/Desktop/Software:/Users/jotieno/Desktop/Software/SPAdes-3.8.2-Darwin/bin:/Users/jotieno/Desktop/Software/QUASR_v7.01:/Users/jotieno/Desktop/Software/VICUNA_v1.3/bin:/Users/jotieno/Desktop/Software/Trimmomatic-0.36:/Users/jotieno/Desktop/Software/fastx_toolkit:/Users/jotieno/Desktop/Software/circos-0.69-4/bin:/Users/jotieno/Desktop/Software/GenomeAnalysisTK-3.7:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/ncbi/blast/bin:/Users/jotieno/.rvm/bin`

**Comment by jrotieno** [comment]
Any updates on this?
still terminal quits and when I redirect the output I get the condo character limit error

**Comment by notestaff** [comment]
( @tomkinsc   MacOS build is disabled for now, right?)

**Comment by tomkinsc** [comment]
Yes, disabled and unsupported until Travis scales up their OSX test infrastructure.

**Comment by dpark01** [comment]
@notestaff the tests do generally pass on OSX however, and most things do work fine, with the exception of a few tools that have OSX issues on bioconda (those unit tests are skipped on OSX). But Travis is exceedingly slow at OSX builds, so we don't enable it. But you can manually run the tests on your own machine at any time.

This issue, however, is not about the viral-ngs code that has test coverage, it's about the easy deploy shell script. It should theoretically work...

**Comment by jrotieno** [comment]
**UPDATE**

I decided to use:
`source activate /Users/jotieno/viral-ngs-etc/conda-env`
instead of
`source easy-deploy-viral-ngs.sh load`
and seems to run well. So I guess that is the way forward for me.

Hopefully it is the same thing and does not mangle things in there and end up with something unintended!

If this is all good and other users do not report problems using the alternative, I am happy to rest the issue.
