### ISSUE TITLE
update to samtools 1.4.1 & pysam 0.11.2.2

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#632]
We're currently on samtools 1.3.1 and pysam 0.9.1. The latest versions of all this allows for direct access of BAM files living on S3 and GCS ([htslib > 1.4](https://github.com/samtools/htslib/releases/tag/1.4)) and some multi-threaded speedups in samtools itself ([samtools > 1.4](https://github.com/samtools/samtools/releases/tag/1.4)).

**Comment by tomkinsc** [comment]
Or [samtools 1.6](https://github.com/samtools/samtools/releases/tag/1.6), with its new `markdup` command (and `-m` `fixmate`), and more efficient sorting.

**Comment by dpark01** [comment]
Bioconda is only at samtools 1.5 at the moment... not sure why.

**Comment by tomkinsc** [comment]
I can look into it. Updates to bioconda really only happen when someone notices out of date packages.
