### ISSUE TITLE
Refactor Snakemake rules to make database paths more flexible

### ISSUE THREAD

**Issue by tomkinsc** [broadinstitute/viral-ngs#639]
The Snakemake implementation of viral-ngs should be refactored to specify the database files not as [`params` block values](https://github.com/broadinstitute/viral-ngs/blob/18c47480a0dbaf9e55e20b065cc6cc10866032e1/pipes/rules/hs_deplete.rules#L33-L34), but rather as inputs so we can, if necessary, wrap them in `remote()` [file wrappers](https://snakemake.readthedocs.io/en/stable/snakefiles/remote_files.html) and have the pipeline source databases from S3 buckets, SFTP sources, etc. Other files may remain local (and be mounted as an internal Docker volume, say, in the case of [dsub](https://github.com/googlegenomics/dsub/blob/master/docs/input_output.md)), or be wrapped by a common remote prefix in the upcoming `4.x` [version](https://bitbucket.org/snakemake/snakemake/src/068fd89bf27a333133c9e99962b6cecf2abbf80f/docs/executable.rst?at=4.x&fileviewer=file-view-default) of snakemake (`--default-remote-provider $REMOTE --default-remote-prefix $PREFIX`).

 In support of this, a config file should be created (`config-cloud.yml`?) that may renamed to (or [imported by](https://github.com/broadinstitute/viral-ngs/pull/627)) `config.yml` on cloud-based pipelines. This new config file will specify database paths with pseudo-protocol prefixes (ex. `s3://`). The rule inputs for the database files will be functions that will [`objectify_remote()`](https://github.com/broadinstitute/viral-ngs/blob/f8a8a699748a0628721799d00867503a72544098/pipes/rules/demux.rules#L18-L31) as necessary so that config files may specify local or remote paths to database resources (or rather, so the user can specify either a local- or remote-focused config file).

By specifying database resources as inputs rather than as params, the pipeline will source them only for the jobs requiring them, obviating the need to, for example, mount (or copy in) the large kraken database for rules/jobs where the database is not required. 

As an additional change, the database paths should perhaps be sourced from environment variables, if present, falling back to the config-specified paths if absent.

An annoying consideration is that while Snakemake can accept local directories as inputs, we may need to explicitly list remote database files via `glob_wildcards()` since the `exists()` function of Snakemake remote providers may not work on partial keys for all providers (i.e. we may not be able to see if a "directory" exists (S3/GS doesn't have true "directories"), but we can usually list the full object keys and match against a pattern). This may be required since the databases are usually specified as paths rather than lists of files (ex. `.bitmask`, `.fasta`, `.srprism.amp`, `.srprism.idx`, `.srprism.imp`, `.srprism.map`, `.srprism.pmp`, `.srprism.rmp`, `.srprism.ss`, `.srprism.ssa`, `.srprism.ssd`, and so on... ).

**Comment by dpark01** [comment]
This all sounds good to me. A few thoughts

- I might actually lean towards making the cloud paths the default (`config.yml`) and the Broad paths the special case scenario (overridden with a yaml import), especially since the cloud paths will always work, and the Broad / local NFS paths are just a speed optimization.
- I like the idea of explicitly naming all the dumb little files with all their extensions--annoying, but it's probably better to be more explicit in general. Actually, you can even create an indexing rule that creates all the dumb little files if the fasta exists but the others don't.
- I like the move to `input:` instead of `params:`. I think it only was in `params:` before as a way of postponing a proper implementation.

**Comment by yesimon** [comment]
Is it possible to specify a local input file but remote file as backup (in cases of a large database that you already have?)

**Comment by dpark01** [comment]
@yesimon the easiest way to do that in Snakemake is to have a local input file for the database, and create a downloader rule that outputs that local file if it doesn't exist.

**Comment by tomkinsc** [comment]
Or to override cloud paths via @notestaff's new yaml import.

**Comment by tomkinsc** [comment]
Maybe we should add upstream Snakemake rules that can download `.tar.gz` or `.lz4` archives of the databases and extract them to the paths expected by the downstream rules.

**Comment by tomkinsc** [comment]
The initial PR to support this has been merged in with #644. A PR to Snakemake with transparent gzip decompression [is open](https://bitbucket.org/snakemake/snakemake/pull-requests/239/add-automatic-decompression-of-s3-objects/diff). Support for gzip decompression in boto would be better, but it is not yet in `botocore`.

**Comment by tomkinsc** [comment]
Closing this for now...
