### ISSUE TITLE
tolerate bad line endings in samplesheets

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#674]
Although most of our csv-reading samplesheet code tolerates MS Excel-generated files (with Mac OS9 line endings), our txt-reading samplesheet code does not. In particular, `util.file.read_tabfile_dict` (and the related `read_tabfile`) are opening files as `'rt'` instead of `'rU'`. This is one of the dumber error modes that frequently happens that Redmond, WA imposes on us, but we must deal with.

**Comment by tomkinsc** [comment]
Do we have example txt sample sheets to test against beyond [the one](https://github.com/broadinstitute/viral-ngs/blob/master/test/input/TestSampleSheet/SampleSheet-custom-1.txt) in the unit test input folder? (If so, we can attach them to this issue thread.)

**Comment by dpark01** [comment]
While we could come up with more, I don't think they'd necessarily explore more corner cases of the code, they'd basically have the same structure.

We could create a file with `\r` and `\r\n` endings, but I'm a little worried that automagic stuff in git might convert them all... we could create a unit test that takes `SampleSheet-custom-1.txt` and rewrites it with a mix of OS9, DOS, and Unix line endings to use as new test inputs. We could do that to the csv files as well.

**Comment by tomkinsc** [comment]
Sounds like a plan. I'll add a helper util somewhere.

**Comment by tomkinsc** [comment]
In #675.
