### ISSUE TITLE
multi-scaffold fails if one scaffold fails

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#740]
The current naive reference selection code tries multiple `_order_and_orient_orig` calls in parallel and picks the best one based on simplistic criteria.

However, [it errors if any of these calls](https://platform.dnanexus.com/projects/F8Zkjz80gKfy3vzy0b0p0G5b/monitor/job/F8ZpYVQ0gKfQzGbG99gJKgY6) fail to scaffold for all segments of all user-provided reference genomes. In real use, a user will likely specify a diverse range of reference genomes from the species that span different clades, so it would be very normal for some of these to fail scaffolding.

I propose changing [this assertion](https://github.com/broadinstitute/viral-ngs/blob/master/assembly.py#L537) to a filter instead (remove all results that do not have the same number of segments as the input) and then throw an assertion if no results remain after filtration (which means all `_order_and_orient_orig` calls failed). Then proceed to choose the best of the remaining genomes.

**Comment by notestaff** [comment]
Maybe instead, just delete the assertion?  Does any downstream code actually rely on us assembling every segment of a multi-segment genome?

**Comment by dpark01** [comment]
Yeah I think multiple alignments of genomes and also iSNV stuff will fail if we don't have all the segments...

**Comment by notestaff** [comment]
What does "fail scaffolding" mean?  Woulldn't _order_and_orient_orig just output a string of Ns for each genome segment, in keeping with "never fail, output degenerate output instead" principle?

**Comment by dpark01** [comment]
It's not what it currently does, but we can move it in that direction.

Right now, there is a failure after order and orient if it doesn't produce the same number of segments as the original, because it's hard/impossible to determine which segment is which, so if we wanted to emit a single "N" for the other missing contigs (in order to do what you propose), we don't know which one the missing one is (without doing something repetitive like aligning again). We could recode the guts a bit to see if we can reliably keep a one-to-one-mapping between input and output segments...

Or, just for now, we could just drop the genomes that "failed" because, most likely, at least one other genome "succeeded"..
