### ISSUE TITLE
unable to download Diamond database

### ISSUE THREAD

**Issue by jb013b** [broadinstitute/viral-ngs#744]
Under setting up analysis for snakemake. The Diamond database has an error prior to downloading. nr.dmnd.gz (*.lz4). The error is "NoSuchKeyThe specified key does not exist".
The url link is: https://storage.googleapis.com/sabeti-public/meta_dbs/nr.dmnd.gz

Where is the best place to find the DIAMOND database?

**Comment by jb013b** [comment]
I found a location for a DIAMOND database.

https://storage.googleapis.com/sabeti-public/meta_dbs/diamond/nr.20170529/nr.dmnd.bz2

**Comment by yesimon** [comment]
Yes - that is the appropriate DB. Will update the link as well

**Comment by jb013b** [comment]
Simon,

Any suggestions on my questions about the snakemake pipeline?

 

james
