### ISSUE TITLE
Allow "demux" on single-sample runs without samplesheet

### ISSUE THREAD

**Issue by tomkinsc** [broadinstitute/viral-ngs#759]
Currently we make assumptions in various places that a sample sheet will be provided for basecalling (and demultiplexing). Our Picard wrapper code for "demux" should be able to run without a samplesheet, if Picard can run without one. Related to this, verify Picard will run on iSeq output.

Should we rename `illumina_demux` to something more generic?

**Comment by dpark01** [comment]
I'm not totally sure, but I think for GitHub to automatically close an issue referenced by a merged PR, you need to precede it with magic words like "fixes" or something like that (I guess "addresses" isn't good enough).

**Comment by dpark01** [comment]
Oh yes, here it is: https://help.github.com/articles/closing-issues-using-keywords/
