### ISSUE TITLE
Pre-formatted nr diamond database link not working

### ISSUE THREAD

**Issue by tyhsu389** [broadinstitute/viral-ngs#803]
Hi,

The link to the nr diamond database on http://viral-ngs.readthedocs.io/en/latest/pipeuse.html appears to be broken.

The hyperlink is: https://storage.googleapis.com/sabeti-public/meta_dbs/nr.dmnd.gz

Thank you,
Tiffany

**Comment by yesimon** [comment]
Please try gs://sabeti-public/meta_dbs/diamond/nr.20170529/nr.dmnd.bz2 or gs://sabeti-public/meta_dbs/diamond/nr.20170529/nr.dmnd (uncompressed version).

The relevant `nodes.dmp` and `prot.accession2taxid.gz` files are in the same directory.
