### ISSUE TITLE
Remove human @SQ lines from bwa-depleted bam files

### ISSUE THREAD

**Issue by tomkinsc** [broadinstitute/viral-ngs#814]
When bwa is used to deplete bam files, it leaves behind `@SQ` lines in the header for the input seqs used (human chr, etc.). It also leaves a `@PG` breadcrumb trail. We should probably remove these from the (unaligned) bam file that is returned.

**Comment by dpark01** [comment]
It also says SO: coordinate which isn't quite right (it's unaligned). Part of me wonders if we should revert the BWA bam depletion approach to do what all the other depletion tools are doing: create a list of IDs and use Picard to Filter the original input (the current implementation uses output that was derived from BWA's output, which is unlike all our other filtration steps). Alternatively there's the "just run RevertSam afterwards" approach.

**Comment by tomkinsc** [comment]
The RevertSam approach is included in PR #791: https://github.com/broadinstitute/viral-ngs/pull/791/files#diff-469a1fc9f03028c6d36de3f66dad5497R589

**Comment by dpark01** [comment]
Should we revisit #791? Last I recall I think you either asked to hold on it for a while, or ... maybe it just fell off my radar and I dropped the ball. But RevertSam should remove all the @SQ lines too.

**Comment by tomkinsc** [comment]
Closed by #791.
