### ISSUE TITLE
pytest error: tempfile.py:368: FileNotFoundError

### ISSUE THREAD

**Issue by tomkinsc** [broadinstitute/viral-ngs#862]
This may be related to changes introduced in #840.

When running pytest, the fixtures responsible for creating temp directories can attempt to create a temp directory within a containing directory that does not exist, resulting in an error from [tempfile.py](https://github.com/python/cpython/blob/master/Lib/tempfile.py#L366): `tempfile.py:368: FileNotFoundError`

How to reproduce (once the expected test output has been updated to what GenBank now returns):
Within [test/integration/test_ncbi.py](https://github.com/broadinstitute/viral-ngs/blob/master/test/integration/test_ncbi.py#L23 ), change `skip_test = True` to `skip_test = False`. 
Then run:
`pytest test/integration/test_ncbi.py`
Note that the issue _does not_ appear when calling one of the test classes directly.
(ex. `pytest test/integration/test_ncbi.py::TestFastaFetch`).

Potentially relevant from the pytest [changelog](https://docs.pytest.org/en/latest/changelog.html) is a change in pytest 3.3.0 related to `testdir `/`tmpdir`: https://github.com/pytest-dev/pytest/issues/2751
Maybe with the upgrade to pytest 3.6.3 in #856, we no longer need the custom tmpdir fixtures in [conftest.py](https://github.com/broadinstitute/viral-ngs/blob/master/conftest.py)?

**Comment by dpark01** [comment]
If you think our custom fixtures could be eliminated by using newly available features in the latest pytest, I’m all for reducing our custom test code.

**Comment by tomkinsc** [comment]
It's worth trying, but since the custom fixtures were added to squash a bug that appeared only intermittently it would be helpful to have @notestaff take a look since he was able to reliably reproduce the issue (by running pytest many times?).

**Comment by dpark01** [comment]
Yeah I actually don’t remember why we have these custom fixtures.. I just remember we tweaked them recently.

**Comment by yesimon** [comment]
pytest doesn't have great handling for ordering tmpfile generation, which was the original purpose to order the module vs function vs session level tmpfiles.

**Comment by notestaff** [comment]
also, pytest doesn't use mkdtemp, which is the safer way to create temdirs.
also, using own fixtures lets us preserve the tempdirs during testing by setting an env var.

i'll push the PR fixing this shortly, the changes are at https://github.com/broadinstitute/viral-ngs/compare/is-fix-test-tempfiles

**Comment by tomkinsc** [comment]
How should we access the tempdir within a test class method, `tempfile.gettempdir()`? Do we really need to add an ugly pytest fixture for it?

**Comment by notestaff** [comment]
I'm not sure I understand.  In what way is adding a test method parameter uglier than adding a line of code that calls tempfile.gettempdir()?

**Comment by tomkinsc** [comment]
IMHO, pytest's param-like fixtures can be ambiguous since it is not always clear where they are defined, especially if in a different scope. The native`unittest` module has `setUp()` `setUpClass()`, which are at least in-scope (and honored by pytest).

**Comment by notestaff** [comment]
While fixtures can get implicitly imported from conftest.py, which can be at the root or in a local dir, it's not the same level of bad as "from X import *", since if it's not local it's in one of the few conftest.py .
