### ISSUE TITLE
assemble_spades: add --always_succeed

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#886]
Problem: currently, post-upload triggered DNAnexus analyses fail routinely due to assembly errors (that should not actually be considered errors in this scenario). [Example](https://platform.dnanexus.com/projects/Bq1xjF0010q3Qv8V70vjXpV8/monitor/analysis/FKgYF3j010q03qpg65V6j5XY) (failure [source](https://platform.dnanexus.com/projects/Bq1xjF0010q3Qv8V70vjXpV8/monitor/job/FKgYYF8010q8kz9kF638bXFQ)).

Solution: add an `--always_succeed` option to `assembly.assemble_spades` (like `assembly.assemble_trinity` already has) and set that option to true for the `demux_plus` WDL workflow (but not for the various `assemble_denovo_*` workflows).

Separately, if we're getting any errors in post-upload depletion jobs, we should bugfix those too. There's no good reason for these steps to ever fail.

**Comment by tomkinsc** [comment]
Merged in #888
