### ISSUE TITLE
everything is single threaded now?

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs#911]
When executing command line viral-ngs in google cloud, either within a conda environment on a manually created VM, or within dsub/PAPIv2, I'm noticing that `--threads 1` is being passed to pretty much every subprocess call.

I note two possible bugs here:
1. Should [this](https://github.com/broadinstitute/viral-ngs/blob/master/util/misc.py#L422) say `cfs_period_us` instead of `cfs_quota_us`?
2. In my environments, `cfs_quota_us` is reporting `-1`, perhaps using that value to denote unlimited quota. This means `available_cpu_count()` is always reporting `1` instead of the number of processors available on the machine. [This line](https://github.com/broadinstitute/viral-ngs/blob/master/util/misc.py#L424) should change to treat `-1` as infinity.

**Comment by tomkinsc** [comment]
Can we close this now that #912 has been merged?

**Comment by dpark01** [comment]
Yes, similar to the other PR, I think @notestaff 's description of PR #912 needed to say "fixes" or "closes" #911 before it merged, in order for merging to close this issue.
